// examples/vue-counter/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import Counter from "./Counter.voo";
import FailMount from "./FailMount.voo";
import LoopEvents from "./LoopEvents.voo";
import ProtocolEvents from "./ProtocolEvents.voo";

const initial = ref(1);
const lastChange = ref<number>();
const visible = ref(true);
const selected = ref<number>();
const protocolVisible = ref(true);
const protocol = ref<string>();
const mountError = ref<string>();
const failedPing = ref(false);
const failedVisible = ref(false);

function receiveMany(index: number, enabled: boolean, label: string) {
  protocol.value = `many:${index}:${enabled}:${label}`;
}
</script>

<template>
  <main>
    <h1>Vooya inside Vue</h1>
    <Counter
      v-if="visible"
      :initial="initial"
      class="counter-host"
      @change="lastChange = $event"
    />
    <p>Vue received: {{ lastChange ?? "no event" }}</p>
    <button @click="initial = 10">Set Vue prop to 10</button>
    <button @click="initial = 11">Set Vue prop to 11</button>
    <button @click="visible = !visible">Toggle Vooya island</button>
    <LoopEvents @choose="selected = $event" />
    <p>Vue loop event: {{ selected ?? "no event" }}</p>
    <ProtocolEvents
      v-if="protocolVisible"
      class="protocol-host"
      @zero="protocol = 'zero'"
      @one="protocol = `one:${$event}`"
      @many="receiveMany"
    />
    <p>Vue protocol event: {{ protocol ?? "no event" }}</p>
    <button @click="protocolVisible = !protocolVisible">Toggle protocol island</button>
    <button @click="failedVisible = true">Mount failing island</button>
    <FailMount v-if="failedVisible" class="failed-host" @error="mountError = $event.stage" @ping="failedPing = true" />
    <p>Vue failed mount: {{ mountError ?? "no error" }}</p>
    <p>Vue failed mount ping: {{ failedPing ? "received" : "none" }}</p>
  </main>
</template>

<style>
main { font-family: system-ui, sans-serif; margin: 2rem; }
.counter-host { margin-block: 1rem; }
</style>

// examples/react-counter/src/App.tsx
import { useState } from "react";
import Counter from "./Counter.voo";
import FailMount from "./FailMount.voo";
import LoopEvents from "./LoopEvents.voo";
import ProtocolEvents from "./ProtocolEvents.voo";

export function App() {
  const [initial, setInitial] = useState(1);
  const [lastChange, setLastChange] = useState<number>();
  const [selected, setSelected] = useState<number>();
  const [visible, setVisible] = useState(true);
  const [protocolVisible, setProtocolVisible] = useState(true);
  const [protocol, setProtocol] = useState<string>();
  const [mountError, setMountError] = useState<string>();
  const [failedPing, setFailedPing] = useState(false);
  const [failedVisible, setFailedVisible] = useState(false);

  return (
    <main>
      <h1>Vooya inside React</h1>
      {visible && (
        <Counter
          initial={initial}
          className="counter-host"
          onChange={(value) => setLastChange(value)}
        />
      )}
      <p>React received: {lastChange ?? "no event"}</p>
      <button onClick={() => setInitial(10)}>Set React prop to 10</button>
      <button onClick={() => setInitial(11)}>Set React prop to 11</button>
      <button onClick={() => setVisible((current) => !current)}>Toggle Vooya island</button>
      <LoopEvents onChoose={(index) => setSelected(index)} />
      <p>React loop event: {selected ?? "no event"}</p>
      {protocolVisible && (
        <ProtocolEvents
          className="protocol-host"
          onZero={() => setProtocol("zero")}
          onOne={(value) => setProtocol(`one:${value}`)}
          onMany={(index, enabled, label) => setProtocol(`many:${index}:${enabled}:${label}`)}
        />
      )}
      <p>React protocol event: {protocol ?? "no event"}</p>
      <button onClick={() => setProtocolVisible((current) => !current)}>Toggle protocol island</button>
      <button onClick={() => setFailedVisible(true)}>Mount failing island</button>
      {failedVisible && <FailMount className="failed-host" onError={(error) => setMountError(error.stage)} onPing={() => setFailedPing(true)} />}
      <p>React failed mount: {mountError ?? "no error"}</p>
      <p>React failed mount ping: {failedPing ? "received" : "none"}</p>
    </main>
  );
}
